# Generated by Django 6.0.2 on 2026-02-26 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_another_language', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DarkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_another_language', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dark_pattern_catalog', to='core.catalog')),
            ],
        ),
    ]
