# Generated by Django 6.0.2 on 2026-02-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_catalog_descriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darkpattern',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='darkpattern',
            name='description',
        ),
        migrations.AddField(
            model_name='darkpattern',
            name='alternatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='darkpattern',
            name='consequences_for_the_user',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='darkpattern',
            name='descriptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='darkpattern',
            name='key_mechanics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='darkpattern',
            name='key_mechanics_video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='darkpattern',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='darkpattern',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='darkpattern',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dark_patterns', to='core.catalog'),
        ),
    ]
