# Generated by Django 6.0.2 on 2026-02-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_darkpattern_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkpattern',
            name='section',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
