# Generated by Django 6.0.2 on 2026-02-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_darkpattern_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darkpattern',
            name='section',
        ),
    ]
