# Generated by Django 6.0.2 on 2026-02-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_darkpattern_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkpattern',
            name='description_for_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='darkpattern',
            name='title_another_language_for_list',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
