# Generated by Django 6.0.2 on 2026-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_darkpattern_description_for_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkpattern',
            name='title_another_language',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
