# Generated by Django 6.0.2 on 2026-02-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_darkpattern_title_another_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darkpattern',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='darkpattern',
            name='title_another_language',
        ),
    ]
