# Generated by Django 6.0.2 on 2026-03-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='created_at',
        ),
        migrations.AddField(
            model_name='study',
            name='author_of_the_article',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='created_year',
            field=models.CharField(default=2025, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='original_title',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
