# Generated by Django 6.0.2 on 2026-03-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_study_created_at_study_author_of_the_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkpattern',
            name='key_mechanics_video',
            field=models.FileField(blank=True, null=True, upload_to='dark_patterns/key_mechanics/'),
        ),
    ]
